export enum RouteDataEnum {
  confirm = 'confirm',
  title = 'head.title',
  meta = 'head.meta',
  possiblePaths = 'resolver.possiblePaths',
  rules = 'resolver.rules',
  mailQueue = 'resolver.mailQueue',
  platformApproval = 'resolver.platformApproval',
  errors = 'resolver.errors',
  regions = 'resolver.region',
  platforms = 'resolver.platforms',
  player = 'resolver.player',
  scoreGroupedByStatus = 'resolver.scoreGroupedByStatus',
  categories = 'resolver.categories',
  categoriesWithRecentTopics = 'resolver.categoriesWithRecentTopics',
  subCategoryWithTopics = 'resolver.subCategoryWithTopics',
  breadcrumbs = 'breadcrumbs',
  topicIncreaseViews = 'resolver.topicIncreaseViews',
  topicWithPosts = 'resolver.topicWithPosts',
  usersOnline = 'resolver.usersOnline',
  topicRead = 'resolver.topicRead',
  steamValidateNames = 'resolver.steamValidateNames',
}
