export enum RouteParamEnum {
  idPlayer = 'idPlayer',
  idUser = 'idUser',
  idCharacter = 'idCharacter',
  idCharacterCostume = 'idCharacterCostume',
  idGame = 'idGame',
  idMode = 'idMode',
  idMiniGame = 'idMiniGame',
  idPlatform = 'idPlatform',
  idStage = 'idStage',
  idScore = 'idScore',
  idScoreApprovalMotive = 'idScoreApprovalMotive',
  idSteamProfile = 'idSteamProfile',
  idPlatforms = 'idPlatforms',
  idGames = 'idGames',
  idMiniGames = 'idMiniGames',
  idModes = 'idModes',
  idStages = 'idStages',
  idCharacterCostumes = 'idCharacterCostumes',

  steamid = 'steamid',

  // OTHERS
  email = 'email',
  username = 'username',
  personaName = 'personaName',
  orderBy = 'orderBy',
  orderByDirection = 'orderByDirection',
  confirmationCode = 'confirmationCode',
  openidReturnTo = 'openid.return_to',
  uuid = 'uuid',
  action = 'action',
  limit = 'limit',
  page = 'page',
  itemsPerPage = 'itemsPerPage',
  type = 'type',
  fromDate = 'fromDate',
  toDate = 'toDate',
  term = 'term',
  worldRecord = 'worldRecord',
  characterWorldRecord = 'characterWorldRecord',
  combinationWorldRecord = 'combinationWorldRecord',
  onlyMyScores = 'onlyMyScores',
  score = 'score',
  key = 'key',
}
